'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MudQCEdit
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''TableRow18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow18 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtKeyNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKeyNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow5 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell39 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell40 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQC48HourViscosity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQC48HourViscosity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow19 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell41 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell42 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCHoldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCHoldValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlQCHighLowFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQCHighLowFlag As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TableRow21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow21 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell45 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell46 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCReTestViscosity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCReTestViscosity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''ddlQCTapeOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQCTapeOut As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlQCTapeIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQCTapeIn As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TableRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCCrack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCCrack As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow3 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell8 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell9 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCPockingStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCPockingStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow4 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell10 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell11 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCPockingEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCPockingEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TableRow16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow16 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''TableCell35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell35 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''TableCell36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell36 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''txtQCNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtQC48HourViscosity0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQC48HourViscosity0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCHoldValue0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCHoldValue0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCHighLowFlag0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCHighLowFlag0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCRetestViscosity0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCRetestViscosity0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCTapeOut0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCTapeOut0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCTapeIn0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCTapeIn0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCCrack0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCCrack0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCPockingStart0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCPockingStart0 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtQCPockingEnd0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCPockingEnd0 As Global.System.Web.UI.WebControls.HiddenField
End Class
